@startuml

Main->WebWorker : start
WebWorker->Main : SCRIPTLOADED
Main->WebWorker : BASEINIT (sends requirejs full path)
WebWorker->Main : BASEINIT_COMPLETE (requirejs loaded..job object instantiated)
WebWorker->Main : BASEINIT_ERROR
Main->WebWorker : DISPATCH
WebWorker->Main : DISPATCH_COMPLETE
WebWorker->Main : DISPATCH_ERROR

@enduml
